# Generated by Django 5.1.15 on 2026-08-11 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('notify_enabled', models.BooleanField(default=True)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جستجوی ذخیره\u200cشده',
                'verbose_name_plural': 'جستجوهای ذخیره\u200cشده',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'درخواست\u200cشده'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('blocked', 'مسدود')], default='requested', max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_relations_as_partner', to='businesses.business')),
                ('supplier_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_relations_as_supplier', to='businesses.business')),
            ],
            options={
                'verbose_name': 'رابطه همکاری',
                'verbose_name_plural': 'روابط همکاری',
                'indexes': [models.Index(fields=['supplier_business', 'status'], name='partners_pa_supplie_5c4650_idx'), models.Index(fields=['partner_business', 'status'], name='partners_pa_partner_ce4261_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier_business', 'partner_business'), name='uniq_partner_relation'), models.CheckConstraint(condition=models.Q(('supplier_business', models.F('partner_business')), _negated=True), name='partner_relation_not_self')],
            },
        ),
        migrations.CreateModel(
            name='SupplierFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_follows', to=settings.AUTH_USER_MODEL)),
                ('follower_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_suppliers', to='businesses.business')),
                ('supplier_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='businesses.business')),
            ],
            options={
                'verbose_name': 'دنبال\u200cکردن تأمین\u200cکننده',
                'verbose_name_plural': 'دنبال\u200cکردن تأمین\u200cکنندگان',
                'constraints': [models.UniqueConstraint(fields=('follower_business', 'supplier_business'), name='uniq_supplier_follow')],
            },
        ),
    ]
