# Generated by Django 5.1.15 on 2026-08-11 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='نام کسب\u200cوکار')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='نامک')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('suspended', 'معلق')], default='active', max_length=20)),
                ('verification_status', models.CharField(choices=[('unverified', 'تأییدنشده'), ('pending', 'در انتظار بررسی'), ('verified', 'تأییدشده'), ('rejected', 'ردشده'), ('suspended', 'معلق')], default='unverified', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کسب\u200cوکار',
                'verbose_name_plural': 'کسب\u200cوکارها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'مالک'), ('manager', 'مدیر'), ('staff', 'کارمند'), ('viewer', 'بازدیدکننده')], default='staff', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('invited', 'دعوت\u200cشده'), ('active', 'فعال'), ('suspended', 'معلق')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضویت',
                'verbose_name_plural': 'عضویت\u200cها',
                'indexes': [models.Index(fields=['business', 'status'], name='businesses__busines_d91c84_idx')],
                'unique_together': {('user', 'business')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='نام انبار')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='businesses.business')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='uniq_warehouse_name_per_business')],
            },
        ),
    ]
