# Generated by Django 5.1.15 on 2026-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_rewrite_capability_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembership',
            name='permissions',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
