"""Give each Business a stored invoice counter, seeded from its history.

Allocation used to pull every invoice number the Business had ever issued into
Python to find the maximum, while holding the row lock every other salesperson
was queued behind. The counter replaces that with one UPDATE.

The backfill is the part that matters: starting every counter at zero would
reissue numbers that already exist and collide with
``uniq_invoice_number_per_seller`` on the next invoice. It reads the same
highest-number-so-far the old code computed, once, here.
"""

from django.db import migrations, models


def seed_counters(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    SalesInvoice = apps.get_model("invoicing", "SalesInvoice")

    highest: dict = {}
    for seller_id, number in SalesInvoice.objects.values_list("seller_business_id", "number"):
        try:
            value = int(str(number).split("-")[-1])
        except (TypeError, ValueError):
            # A number that was never generated by allocate_number. Ignoring it
            # is right: the counter must not be dragged forward by something the
            # sequence did not produce.
            continue
        highest[seller_id] = max(highest.get(seller_id, 0), value)

    for business_id, value in highest.items():
        Business.objects.filter(pk=business_id).update(invoice_sequence=value)


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0004_alter_businessmembership_permissions"),
        ("invoicing", "0002_salesinvoice_uniq_invoice_per_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="invoice_sequence",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(seed_counters, migrations.RunPython.noop),
    ]
