# Generated by Django 5.1.15 on 2026-08-11 11:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('inventory', '0001_initial'),
        ('purchase_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_sqm', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='متراژ رزرو')),
                ('status', models.CharField(choices=[('requested', 'درخواست\u200cشده'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده'), ('expired', 'منقضی'), ('converted', 'تبدیل به فروش')], default='requested', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('extended_count', models.PositiveSmallIntegerField(default=0)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='علت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_decided', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.inventorylot')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_requested', to=settings.AUTH_USER_MODEL)),
                ('requester_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='businesses.business')),
                ('seller_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.business')),
                ('source_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='purchase_requests.purchaseoffer')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller_business', 'status'], name='reservation_seller__d74e16_idx'), models.Index(fields=['requester_business', 'status'], name='reservation_request_b3c57e_idx'), models.Index(fields=['status', 'expires_at'], name='reservation_status_f2f985_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_sqm__gt', 0)), name='reservation_quantity_positive')],
            },
        ),
    ]
