# Generated by Django 5.1.15 on 2026-08-11 09:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'سطح قیمت',
                'verbose_name_plural': 'سطوح قیمت',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LotPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('unit', models.CharField(choices=[('per_sqm', 'به ازای متر مربع'), ('per_slab', 'به ازای اسلب'), ('inquiry_only', 'فقط استعلام')], default='per_sqm', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.inventorylot')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_prices', to='pricing.pricetier')),
            ],
            options={
                'verbose_name': 'قیمت محموله',
                'verbose_name_plural': 'قیمت محموله\u200cها',
                'constraints': [models.UniqueConstraint(fields=('lot', 'tier'), name='uniq_price_per_lot_tier')],
            },
        ),
    ]
