# Generated by Django 5.1.15 on 2026-08-11 14:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_uniq_linked_business_per_business'),
        ('inventory', '0002_alter_inventorylot_visibility'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='مبلغ')),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('unit', models.CharField(choices=[('per_sqm', 'به ازای متر مربع'), ('per_slab', 'به ازای اسلب'), ('inquiry_only', 'فقط استعلام')], default='per_sqm', max_length=20, verbose_name='واحد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_prices', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_prices_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_prices', to='inventory.inventorylot')),
            ],
            options={
                'verbose_name': 'قیمت اختصاصی مخاطب',
                'verbose_name_plural': 'قیمت\u200cهای اختصاصی مخاطبین',
                'ordering': ['contact__display_name'],
                'indexes': [models.Index(fields=['lot', 'contact'], name='pricing_con_lot_id_b0d6a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'lot'), name='uniq_price_per_contact_lot')],
            },
        ),
    ]
