# Generated by Django 5.2.17 on 2026-08-21 12:48

from django.db import migrations, models


def clean_legacy_validity(apps, schema_editor):
    LotPrice = apps.get_model("pricing", "LotPrice")
    LotPrice.objects.filter(price_valid_for_days__lt=1).update(price_valid_for_days=1)
    LotPrice.objects.filter(price_valid_for_days__gt=365).update(price_valid_for_days=365)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventorylot_creation_token_and_more'),
        ('pricing', '0004_simplify_price_semantics'),
    ]

    operations = [
        migrations.RunPython(clean_legacy_validity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='lotprice',
            constraint=models.CheckConstraint(condition=models.Q(('price_valid_for_days__gte', 1), ('price_valid_for_days__lte', 365)), name='price_valid_days_range'),
        ),
    ]
