# Generated by Django 5.1.15 on 2026-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('login', 'ورود'), ('customer', 'تأیید مشتری')], default='login', max_length=20),
        ),
    ]
