# Generated by Django 5.2.17 on 2026-08-13 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpchallenge_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequestThrottle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('phone', 'شماره'), ('address', 'نشانی')], max_length=20)),
                ('key', models.CharField(max_length=120)),
                ('window_started_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_request_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'محدودیت درخواست کد',
                'verbose_name_plural': 'محدودیت\u200cهای درخواست کد',
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='uniq_otp_throttle_key')],
            },
        ),
    ]
