# Generated by Django 5.1.15 on 2026-08-11 10:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('stone_type', models.CharField(blank=True, max_length=100, verbose_name='نوع سنگ')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='دسته\u200cبندی')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='رنگ')),
                ('application', models.CharField(blank=True, max_length=150, verbose_name='کاربرد مورد نظر')),
                ('required_qty_sqm', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='متراژ مورد نیاز')),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ضخامت (mm)')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('acceptable_grade', models.CharField(blank=True, max_length=50, verbose_name='سورت قابل قبول')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='بودجه تقریبی (به ازای متر)')),
                ('budget_currency', models.CharField(default='IRR', max_length=3)),
                ('destination_city', models.CharField(blank=True, max_length=100, verbose_name='شهر مقصد')),
                ('required_by', models.DateField(blank=True, null=True, verbose_name='تاریخ نیاز')),
                ('similar_accepted', models.BooleanField(default=True, verbose_name='پذیرش مشابه')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('open', 'باز'), ('matching', 'در حال تطبیق'), ('offered', 'پیشنهاد دریافت\u200cشده'), ('closed', 'بسته'), ('cancelled', 'لغو شده')], default='open', max_length=20)),
                ('is_public_to_network', models.BooleanField(default=True, help_text='قابل مشاهده برای کسب\u200cوکارهای عضو شبکه (نه حراج عمومی)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست خرید',
                'verbose_name_plural': 'درخواست\u200cهای خرید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('offered_qty_sqm', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'ارسال\u200cشده'), ('withdrawn', 'پس گرفته\u200cشده'), ('accepted', 'پذیرفته\u200cشده'), ('rejected', 'ردشده')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_offers_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_offers', to='inventory.inventorylot')),
                ('seller_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_offers', to='businesses.business')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='purchase_requests.purchaserequest')),
            ],
            options={
                'verbose_name': 'پیشنهاد فروش',
                'verbose_name_plural': 'پیشنهادهای فروش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='purchase_re_status_7d9b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['business', 'status'], name='purchase_re_busines_f83bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['stone_type', 'color'], name='purchase_re_stone_t_dee23c_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'submitted')), fields=('purchase_request', 'seller_business'), name='uniq_open_offer_per_seller_pr'),
        ),
    ]
