# Generated by Django 5.1.15 on 2026-08-12 17:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_rewrite_capability_codes'),
        ('inventory', '0007_application_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_qty_sqm', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='متراژ درخواستی')),
                ('proposed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت پیشنهادی')),
                ('buyer_note', models.TextField(blank=True, verbose_name='توضیح خریدار')),
                ('final_qty_sqm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='متراژ نهایی')),
                ('final_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت نهایی')),
                ('seller_note', models.TextField(blank=True, verbose_name='توضیح فروشنده')),
                ('status', models.CharField(choices=[('sent', 'ارسال شده'), ('accepted', 'توافق شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده'), ('completed', 'فروش نهایی شد')], default='sent', max_length=20)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_purchase_requests', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_purchase_requests_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='inventory.inventorylot', verbose_name='محصول')),
                ('seller_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_purchase_requests', to='businesses.business')),
            ],
            options={
                'verbose_name': 'درخواست خرید',
                'verbose_name_plural': 'درخواست\u200cهای خرید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counterparty_type', models.CharField(choices=[('business', 'همکار'), ('customer', 'مشتری')], default='business', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='موبایل مشتری')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('stone_type', models.CharField(blank=True, max_length=100, verbose_name='نوع سنگ')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='سورت')),
                ('quantity_sqm', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='متراژ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت واحد')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='مبلغ کل')),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('finalized_at', models.DateTimeField(verbose_name='تاریخ نهایی شدن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_finalized', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='inventory.inventorylot')),
                ('purchase_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade', to='trading.purchaserequest')),
                ('seller_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='businesses.business')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
                'ordering': ['-finalized_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['seller_business', 'status', '-created_at'], name='trading_pur_seller__854b66_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['buyer_business', 'status', '-created_at'], name='trading_pur_buyer_b_6b9ca6_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('seller_business', models.F('buyer_business')), _negated=True), name='purchase_request_not_self'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['seller_business', '-finalized_at'], name='trading_tra_seller__aecd63_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['buyer_business', '-finalized_at'], name='trading_tra_buyer_b_43ed3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('buyer_business__isnull', False), ('counterparty_type', 'business')), models.Q(('buyer_business__isnull', True), ('counterparty_type', 'customer')), _connector='OR'), name='trade_counterparty_matches_type'),
        ),
    ]
