# Generated by Django 5.1.15 on 2026-08-13 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_invoice_sequence'),
        ('inventory', '0009_lotmedia_uniq_primary_media_per_lot'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='submission_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_id__isnull', False)), fields=('seller_business', 'submission_id'), name='uniq_trade_per_submission'),
        ),
    ]
