# Generated by Django 5.1.15 on 2026-08-13 13:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_lotmedia_uniq_primary_media_per_lot'),
        ('trading', '0002_trade_submission_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity_sqm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت واحد'),
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('stone_type', models.CharField(blank=True, max_length=100, verbose_name='نوع سنگ')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='سورت')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='متراژ')),
                ('unit', models.CharField(default='متر مربع', max_length=20, verbose_name='واحد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت واحد')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='جمع')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_items', to='inventory.inventorylot')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trading.trade')),
            ],
            options={
                'verbose_name': 'ردیف معامله',
                'verbose_name_plural': 'ردیف\u200cهای معامله',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
