# Generated by Django 5.2.17 on 2026-08-23 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_replace_request_capabilities'),
        ('inventory', '0014_product_private_details'),
        ('trading', '0005_trade_proposals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trade',
            name='trade_counterparty_matches_type',
        ),
        migrations.AddField(
            model_name='trade',
            name='local_counterparty_id_snapshot',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='local_counterparty_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trade',
            name='counterparty_type',
            field=models.CharField(choices=[('business', 'همکار'), ('local', 'همکار محلی'), ('customer', 'مشتری')], default='business', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('buyer_business__isnull', False), ('counterparty_type', 'business')), models.Q(('buyer_business__isnull', True), ('counterparty_type', 'local'), ('local_counterparty_id_snapshot__isnull', False)), models.Q(('buyer_business__isnull', True), ('counterparty_type', 'customer'), ('local_counterparty_id_snapshot__isnull', True)), _connector='OR'), name='trade_counterparty_matches_type'),
        ),
    ]
