# Generated by Django 5.1.15 on 2026-08-11 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200, verbose_name='نام / نام کسب\u200cوکار')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='موبایل/تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_customer', models.BooleanField(default=False, verbose_name='مشتری')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='تأمین\u200cکننده')),
                ('is_trader', models.BooleanField(default=False, verbose_name='واسطه')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('linked_business', models.ForeignKey(blank=True, help_text='اتصال اختیاری به یک همکار تأییدشده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contacts', to='businesses.business')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطبین',
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='contacts_co_busines_1615cf_idx'), models.Index(fields=['business', 'display_name'], name='contacts_co_busines_520d20_idx')],
            },
        ),
    ]
