# Generated by Django 5.1.15 on 2026-08-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('contacts', '0002_uniq_linked_business_per_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='linked_business',
            field=models.ForeignKey(blank=True, help_text='اتصال اختیاری به یک همکار در سنگا', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contacts', to='businesses.business'),
        ),
    ]
