# Generated by Django 5.2.17 on 2026-08-23 19:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0007_replace_request_capabilities'),
        ('inventory', '0014_product_private_details'),
        ('invoicing', '0005_chequeevent_chequereceivable_and_more'),
        ('marketplace', '0002_delete_savedsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInquiryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_inquiry_batches', to='businesses.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال\u200cشده'), ('responded', 'پاسخ\u200cداده\u200cشده'), ('converted_to_invoice', 'تبدیل\u200cشده به فاکتور'), ('closed', 'بسته\u200cشده'), ('cancelled', 'لغوشده')], default='sent', max_length=24)),
                ('buyer_note', models.CharField(blank=True, max_length=500)),
                ('seller_note', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_partner_inquiries', to='businesses.business')),
                ('converted_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_partner_inquiry', to='invoicing.salesinvoice')),
                ('seller_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_partner_inquiries', to='businesses.business')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='marketplace.partnerinquirybatch')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerInquiryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('stone_type', models.CharField(blank=True, max_length=100)),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(default='متر مربع', max_length=20)),
                ('availability_snapshot', models.CharField(blank=True, max_length=40)),
                ('availability_checked_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('price_requires_confirmation', models.BooleanField(default=True)),
                ('offered_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('offered_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('seller_note', models.CharField(blank=True, max_length=250)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='marketplace.partnerinquiry')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorylot')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='partnerinquirybatch',
            constraint=models.UniqueConstraint(fields=('buyer_business', 'submission_id'), name='uniq_partner_inquiry_batch_submission'),
        ),
        migrations.AddConstraint(
            model_name='partnerinquiry',
            constraint=models.CheckConstraint(condition=models.Q(('buyer_business', models.F('seller_business')), _negated=True), name='partner_inquiry_not_self'),
        ),
        migrations.AddConstraint(
            model_name='partnerinquiry',
            constraint=models.UniqueConstraint(fields=('batch', 'seller_business'), name='uniq_inquiry_seller_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='partnerinquiryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_requested__gt', 0)), name='partner_inquiry_quantity_positive'),
        ),
    ]
