# Generated by Django 5.1.15 on 2026-08-11 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='موبایل')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('viewed', 'دیده\u200cشده'), ('contacted', 'تماس گرفته\u200cشده'), ('negotiating', 'در حال مذاکره'), ('converted', 'تبدیل\u200cشده'), ('closed', 'بسته'), ('lost', 'از دست\u200cرفته')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('storefront', 'ویترین'), ('lot_detail', 'صفحه محموله'), ('custom_catalog', 'کاتالوگ اختصاصی'), ('share', 'اشتراک\u200cگذاری'), ('other', 'سایر')], default='storefront', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='businesses.business')),
                ('custom_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catalog.customcatalog')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='inventory.inventorylot')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استعلام',
                'verbose_name_plural': 'استعلام\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status', 'created_at'], name='inquiries_i_busines_c297aa_idx')],
            },
        ),
    ]
