# Generated by Django 5.1.15 on 2026-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='source',
            field=models.CharField(choices=[('storefront', 'ویترین'), ('lot_detail', 'صفحه محموله'), ('custom_catalog', 'کاتالوگ اختصاصی'), ('share', 'اشتراک\u200cگذاری'), ('marketplace', 'بازار همکاران'), ('other', 'سایر')], default='storefront', max_length=32),
        ),
    ]
