# Generated by Django 5.1.15 on 2026-08-12 17:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_rewrite_capability_codes'),
        ('inquiries', '0002_alter_inquiry_source'),
        ('inventory', '0007_application_taxonomy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='assignee',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='source',
            field=models.CharField(choices=[('public_search', 'جستجوی عمومی'), ('storefront', 'ویترین'), ('item_detail', 'صفحه محصول'), ('share_link', 'لینک اشتراک'), ('custom_catalog', 'کاتالوگ'), ('marketplace', 'بازار همکاران'), ('other', 'سایر')], default='public_search', max_length=32),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته\u200cشده'), ('converted', 'تبدیل به فروش'), ('closed', 'بسته')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='موبایل')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, verbose_name='یادداشت فروشنده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_leads', to='businesses.business')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='inquiries.customerlead'),
        ),
        migrations.CreateModel(
            name='InquiryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('requested_qty_sqm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='متراژ درخواستی')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inquiries.inquiry')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_items', to='inventory.inventorylot')),
            ],
            options={
                'verbose_name': 'ردیف استعلام',
                'verbose_name_plural': 'ردیف\u200cهای استعلام',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='customerlead',
            index=models.Index(fields=['business', '-updated_at'], name='inquiries_c_busines_1f4259_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerlead',
            constraint=models.UniqueConstraint(fields=('business', 'phone'), name='uniq_lead_phone_per_business'),
        ),
        migrations.AddConstraint(
            model_name='inquiryitem',
            constraint=models.UniqueConstraint(fields=('inquiry', 'item'), name='uniq_item_per_inquiry'),
        ),
    ]
