# Generated by Django 5.1.15 on 2026-08-13 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_alter_businessmembership_permissions'),
        ('catalog', '0002_customcatalog_mode_customcatalog_rules_and_more'),
        ('inquiries', '0004_backfill_leads_and_statuses'),
        ('inventory', '0008_lotmedia_terminology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='submission_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_id__isnull', False)), fields=('submission_id', 'business'), name='uniq_inquiry_per_submission_and_seller'),
        ),
    ]
