# Generated by Django 5.2.17 on 2026-09-02 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_business_storefront_token'),
        ('inquiries', '0005_inquiry_submission_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlead',
            name='category',
            field=models.CharField(choices=[('builder', 'سازنده'), ('consumer', 'مصرف\u200cکننده نهایی'), ('warehouse', 'انباردار'), ('contractor', 'پیمانکار'), ('architect', 'معمار / طراح'), ('partner', 'فروشنده / همکار'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='customerlead',
            name='crm_status',
            field=models.CharField(choices=[('new', 'مشتری جدید'), ('active', 'در حال بررسی'), ('negotiating', 'در حال مذاکره'), ('won', 'خرید انجام\u200cشده'), ('inactive', 'غیرفعال')], default='new', max_length=20, verbose_name='وضعیت ارتباط'),
        ),
        migrations.AddField(
            model_name='customerlead',
            name='current_needs',
            field=models.TextField(blank=True, verbose_name='نیاز فعلی'),
        ),
        migrations.AddField(
            model_name='customerlead',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها'),
        ),
        migrations.CreateModel(
            name='CustomerFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160, verbose_name='موضوع')),
                ('scheduled_for', models.DateTimeField(verbose_name='زمان پیگیری')),
                ('reminder_minutes', models.PositiveIntegerField(default=60, verbose_name='دقایق یادآوری')),
                ('remind_at', models.DateTimeField(db_index=True, verbose_name='زمان یادآوری')),
                ('priority', models.CharField(choices=[('normal', 'عادی'), ('high', 'مهم'), ('urgent', 'فوری')], default='normal', max_length=12, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی\u200cشده'), ('completed', 'انجام\u200cشده'), ('postponed', 'به\u200cتعویق\u200cافتاده'), ('cancelled', 'لغوشده')], default='scheduled', max_length=12, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('related_context', models.CharField(blank=True, max_length=255, verbose_name='موضوع مرتبط')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_followups', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_followups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_followups', to='inquiries.customerlead')),
            ],
            options={
                'verbose_name': 'پیگیری مشتری',
                'verbose_name_plural': 'پیگیری\u200cهای مشتری',
                'ordering': ['scheduled_for', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='متن یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notes', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='inquiries.customerlead')),
            ],
            options={
                'verbose_name': 'یادداشت مشتری',
                'verbose_name_plural': 'یادداشت\u200cهای مشتری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpReminderRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_reads', to='inquiries.customerfollowup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_followup_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خواندن یادآوری پیگیری',
                'verbose_name_plural': 'خواندن\u200cهای یادآوری پیگیری',
            },
        ),
        migrations.AddIndex(
            model_name='customerfollowup',
            index=models.Index(fields=['business', 'status', 'scheduled_for'], name='inquiries_c_busines_13de19_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfollowup',
            index=models.Index(fields=['customer', 'status', 'scheduled_for'], name='inquiries_c_custome_d58caa_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerfollowup',
            constraint=models.CheckConstraint(condition=models.Q(('reminder_minutes__lte', 10080)), name='followup_reminder_within_one_week'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['business', 'customer', '-created_at'], name='inquiries_c_busines_0851bd_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminderread',
            index=models.Index(fields=['user', 'read_at'], name='inquiries_f_user_id_8e86af_idx'),
        ),
        migrations.AddConstraint(
            model_name='followupreminderread',
            constraint=models.UniqueConstraint(fields=('followup', 'user'), name='uniq_followup_reminder_read_per_user'),
        ),
    ]
