# Generated by Django 5.1.15 on 2026-08-11 12:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('sale', 'فروش به مخاطب'), ('purchase', 'خرید از مخاطب'), ('payment_received', 'دریافت وجه'), ('payment_made', 'پرداخت وجه'), ('adjust_debit', 'بدهکار کردن مخاطب'), ('adjust_credit', 'بستانکار کردن مخاطب'), ('reversal', 'برگشت سند')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ')),
                ('balance_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='شرح')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع/شماره سند')),
                ('occurred_on', models.DateField(verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='businesses.business')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('related_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='inventory.inventorylot')),
                ('related_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='reservations.reservation')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='accounting.ledgerentry')),
            ],
            options={
                'verbose_name': 'سند حسابداری',
                'verbose_name_plural': 'اسناد حسابداری',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['business', 'contact', 'created_at'], name='accounting__busines_6005c2_idx'), models.Index(fields=['contact', 'created_at'], name='accounting__contact_8917db_idx'), models.Index(fields=['business', 'occurred_on'], name='accounting__busines_27d1af_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_positive')],
            },
        ),
    ]
