# Generated by Django 5.1.15 on 2026-08-11 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('businesses', '0001_initial'),
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type__in', ('sale', 'purchase')), ('related_reservation__isnull', False)), fields=('business', 'related_reservation'), name='uniq_trade_entry_per_reservation'),
        ),
    ]
