# Generated by Django 5.1.15 on 2026-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ledgerentry_reversed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('sale', 'فروش'), ('purchase', 'خرید'), ('payment_received', 'دریافت'), ('payment_made', 'پرداخت'), ('adjust_debit', 'اصلاح بدهکار'), ('adjust_credit', 'اصلاح بستانکار'), ('reversal', 'برگشت سند')], max_length=20),
        ),
    ]
