# Generated by Django 5.2.17 on 2026-08-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_ledger_contact_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=140),
        ),
    ]
