# Generated by Django 5.2.17 on 2026-08-23 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_historical_invoice_entries(apps, schema_editor):
    """Attach existing reciprocal trade entries to their invoice without reposting."""
    LedgerEntry = apps.get_model("accounting", "LedgerEntry")
    SalesInvoice = apps.get_model("invoicing", "SalesInvoice")
    for invoice in SalesInvoice.objects.exclude(trade__isnull=True).iterator():
        LedgerEntry.objects.filter(
            related_trade_id=invoice.trade_id,
            business_id__in=[invoice.seller_business_id, invoice.buyer_business_id],
            related_invoice__isnull=True,
        ).update(related_invoice_id=invoice.id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_ledgerentry_idempotency_key'),
        ('businesses', '0007_replace_request_capabilities'),
        ('contacts', '0004_remove_contact_types'),
        ('inventory', '0014_product_private_details'),
        ('invoicing', '0005_chequeevent_chequereceivable_and_more'),
        ('purchase_requests', '0001_initial'),
        ('trading', '0005_trade_proposals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='local_counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='invoicing.localcounterparty', verbose_name='همکار محلی'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='related_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='invoicing.salesinvoice'),
        ),
        migrations.RunPython(link_historical_invoice_entries, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['business', 'local_counterparty', 'created_at'], name='accounting__busines_8c749e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_ledger_idempotency_key'),
        ),
    ]
