# Generated by Django 5.1.15 on 2026-08-11 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='inventory.inventorylot')),
            ],
            options={
                'verbose_name': 'نتیجه تطبیق',
                'verbose_name_plural': 'نتایج تطبیق',
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
