# Generated by Django 5.1.15 on 2026-08-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('purchase_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='purchase_requests.purchaserequest'),
        ),
        migrations.AddConstraint(
            model_name='matchresult',
            constraint=models.UniqueConstraint(fields=('purchase_request', 'lot'), name='uniq_match_pr_lot'),
        ),
    ]
