# Generated by Django 5.1.15 on 2026-08-11 09:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_code', models.CharField(max_length=64, verbose_name='کد محموله')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('available', 'موجود'), ('reservation_pending', 'در انتظار رزرو'), ('reserved', 'رزرو شده'), ('partially_sold', 'فروش جزئی'), ('sold', 'فروخته\u200cشده'), ('expired', 'منقضی'), ('hidden', 'مخفی'), ('needs_confirmation', 'نیاز به تأیید')], default='draft', max_length=32)),
                ('visibility', models.CharField(choices=[('private', 'داخلی'), ('selected_partners', 'شرکای انتخابی'), ('all_partners', 'همه شرکای تأییدشده'), ('customer_catalog', 'کاتالوگ مشتری'), ('public', 'عمومی')], default='private', max_length=32)),
                ('available_sqm', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('original_sqm', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('slab_count', models.PositiveIntegerField(blank=True, null=True)),
                ('bundle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('processing_type', models.CharField(blank=True, max_length=100)),
                ('min_sale_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ready_for_loading_at', models.DateField(blank=True, null=True)),
                ('photographed_at', models.DateField(blank=True, null=True)),
                ('inventory_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('defect_notes', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent_sale', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='businesses.business')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='businesses.warehouse')),
            ],
            options={
                'verbose_name': 'محموله موجودی',
                'verbose_name_plural': 'محموله\u200cهای موجودی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LotMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], default='image', max_length=16)),
                ('file', models.FileField(upload_to='lot_media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lot_media/thumbs/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.inventorylot')),
            ],
            options={
                'verbose_name': 'رسانه محموله',
                'verbose_name_plural': 'رسانه\u200cهای محموله',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commercial_name', models.CharField(max_length=200, verbose_name='نام تجاری')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220)),
                ('stone_type', models.CharField(blank=True, max_length=100, verbose_name='نوع سنگ')),
                ('quarry_region', models.CharField(blank=True, max_length=150, verbose_name='معدن/منطقه')),
                ('primary_color', models.CharField(blank=True, max_length=100, verbose_name='رنگ غالب')),
                ('pattern', models.CharField(blank=True, max_length=150, verbose_name='طرح/بافت')),
                ('vein_notes', models.CharField(blank=True, max_length=255)),
                ('applications', models.JSONField(blank=True, default=list)),
                ('interior_suitable', models.BooleanField(default=True)),
                ('exterior_suitable', models.BooleanField(default=False)),
                ('technical_notes', models.TextField(blank=True)),
                ('description_public', models.TextField(blank=True, verbose_name='توضیح مشتری')),
                ('description_professional', models.TextField(blank=True, verbose_name='توضیح حرفه\u200cای')),
                ('alt_names', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['commercial_name'],
            },
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.product'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('business', 'slug'), name='uniq_product_slug_per_business'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['business', 'status'], name='inventory_i_busines_5825a5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['business', 'inventory_confirmed_at'], name='inventory_i_busines_e24dce_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['visibility', 'status', 'updated_at'], name='inventory_i_visibil_004429_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(fields=('business', 'lot_code'), name='uniq_lot_code_per_business'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('available_sqm__gte', 0)), name='lot_available_sqm_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('original_sqm__gte', 0)), name='lot_original_sqm_nonnegative'),
        ),
    ]
