# Generated by Django 5.1.15 on 2026-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylot',
            name='visibility',
            field=models.CharField(choices=[('private', 'داخلی'), ('selected_partners', 'شرکای تأییدشده (قدیمی)'), ('all_partners', 'شرکای تأییدشده'), ('customer_catalog', 'کاتالوگ مشتری'), ('public', 'عمومی')], default='private', max_length=32),
        ),
    ]
