# Generated by Django 5.1.15 on 2026-08-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_application_taxonomy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotmedia',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'رسانه محصول', 'verbose_name_plural': 'رسانه\u200cهای محصول'},
        ),
    ]
