# Generated by Django 5.1.15 on 2026-08-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_lotmedia_terminology'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lotmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('lot',), name='uniq_primary_media_per_lot'),
        ),
    ]
