# Generated by Django 5.2.17 on 2026-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_lotmedia_uniq_primary_media_per_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('stone_type', 'نوع سنگ'), ('color', 'رنگ غالب'), ('processing_type', 'نوع فرآوری')], max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'واژه\u200cنامه',
                'verbose_name_plural': 'واژه\u200cنامه\u200cها',
                'ordering': ['kind', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='uniq_vocabulary_term')],
            },
        ),
    ]
