# Generated by Django 5.2.17 on 2026-08-21 12:48

from django.db import migrations, models


def clean_legacy_lots(apps, schema_editor):
    InventoryLot = apps.get_model("inventory", "InventoryLot")
    InventoryLot.objects.filter(length_cm__lte=0).update(length_cm=None)
    InventoryLot.objects.filter(width_cm__lte=0).update(width_cm=None)
    InventoryLot.objects.filter(thickness_mm__lte=0).update(thickness_mm=None)
    InventoryLot.objects.filter(min_sale_qty__lt=0).update(min_sale_qty=0)
    InventoryLot.objects.filter(stock_valid_for_days__lt=1).update(stock_valid_for_days=1)
    InventoryLot.objects.filter(stock_valid_for_days__gt=365).update(stock_valid_for_days=365)
    InventoryLot.objects.filter(available_sqm=0, availability_status="available").update(
        availability_status="unavailable"
    )
    for lot in InventoryLot.objects.filter(
        available_sqm__isnull=False,
        min_sale_qty__gt=models.F("available_sqm"),
    ).iterator():
        lot.min_sale_qty = lot.available_sqm
        lot.save(update_fields=["min_sale_qty"])


def create_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    statements = (
        "CREATE EXTENSION IF NOT EXISTS pg_trgm",
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS inventory_product_name_trgm "
        "ON inventory_product USING gin (UPPER(commercial_name) gin_trgm_ops)",
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS inventory_product_suffix_trgm "
        "ON inventory_product USING gin (UPPER(name_suffix) gin_trgm_ops)",
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS inventory_lot_code_trgm "
        "ON inventory_inventorylot USING gin (UPPER(lot_code) gin_trgm_ops)",
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS inventory_lot_process_trgm "
        "ON inventory_inventorylot USING gin (UPPER(processing_type) gin_trgm_ops)",
    )
    for statement in statements:
        schema_editor.execute(statement)


def drop_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for name in (
        "inventory_product_name_trgm",
        "inventory_product_suffix_trgm",
        "inventory_lot_code_trgm",
        "inventory_lot_process_trgm",
    ):
        schema_editor.execute(f'DROP INDEX CONCURRENTLY IF EXISTS "{name}"')


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('businesses', '0007_replace_request_capabilities'),
        ('inventory', '0012_product_inventory_simplification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylot',
            name='creation_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['business', 'is_visible', 'availability_status', 'status', 'deleted_at'], name='inventory_lot_sell_idx'),
        ),
        migrations.RunPython(clean_legacy_lots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('length_cm__isnull', True), ('length_cm__gt', 0), _connector='OR'), name='lot_length_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('width_cm__isnull', True), ('width_cm__gt', 0), _connector='OR'), name='lot_width_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('thickness_mm__isnull', True), ('thickness_mm__gt', 0), _connector='OR'), name='lot_thickness_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('min_sale_qty__gte', 0)), name='lot_min_sale_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('stock_valid_for_days__gte', 1), ('stock_valid_for_days__lte', 365)), name='lot_stock_valid_days_range'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('available_sqm__isnull', True), ('min_sale_qty__lte', models.F('available_sqm')), _connector='OR'), name='lot_min_sale_within_stock'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('availability_status', 'available'), ('available_sqm', 0), _negated=True), name='lot_zero_stock_not_available'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_token__isnull', False)), fields=('business', 'creation_token'), name='uniq_lot_creation_token'),
        ),
        migrations.RunPython(create_search_indexes, drop_search_indexes),
    ]
