# Generated by Django 5.1.15 on 2026-08-12 17:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_rewrite_capability_codes'),
        ('inventory', '0007_application_taxonomy'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, verbose_name='شماره فاکتور')),
                ('counterparty_type', models.CharField(choices=[('business', 'همکار'), ('customer', 'مشتری')], default='business', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='موبایل مشتری')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='نام خریدار')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('cancelled', 'باطل شده')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='جمع کل')),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('seller_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='businesses.business')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='trading.trade')),
            ],
            options={
                'verbose_name': 'فاکتور فروش',
                'verbose_name_plural': 'فاکتورهای فروش',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('stone_type', models.CharField(blank=True, max_length=100, verbose_name='نوع سنگ')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='سورت')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='مقدار')),
                ('unit', models.CharField(default='متر مربع', max_length=20, verbose_name='واحد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت واحد')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='جمع')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.salesinvoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='inventory.inventorylot')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['seller_business', '-issue_date'], name='invoicing_s_seller__e7b80d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['buyer_business', '-issue_date'], name='invoicing_s_buyer_b_7d9161_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(fields=('seller_business', 'number'), name='uniq_invoice_number_per_seller'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('buyer_business__isnull', False), ('counterparty_type', 'business')), models.Q(('buyer_business__isnull', True), ('counterparty_type', 'customer')), _connector='OR'), name='invoice_counterparty_matches_type'),
        ),
    ]
