# Generated by Django 5.2.17 on 2026-08-23 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_lifecycle_audit(apps, schema_editor):
    SalesInvoice = apps.get_model("invoicing", "SalesInvoice")
    SalesInvoice.objects.exclude(status="draft").update(
        issued_at=models.F("updated_at")
    )
    SalesInvoice.objects.filter(status="cancelled").update(
        cancelled_at=models.F("updated_at"),
        cancel_reason="ابطال ثبت‌شده پیش از افزوده‌شدن تاریخچه علت",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_replace_request_capabilities'),
        ('invoicing', '0003_invoice_document_system'),
        ('trading', '0005_trade_proposals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplate',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='علت ابطال'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='replaces_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_invoice', to='invoicing.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='submission_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='seller_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='businesses.business'),
        ),
        migrations.RunPython(backfill_lifecycle_audit, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_id__isnull', False)), fields=('seller_business', 'submission_id'), name='uniq_invoice_submission_per_seller'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('number', ''), _negated=True), _connector='OR'), name='invoice_finalized_has_number'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('issued_at__isnull', False), _connector='OR'), name='invoice_finalized_has_issued_at'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancelled_at__isnull', False), models.Q(('cancel_reason', ''), _negated=True)), _connector='OR'), name='invoice_cancelled_has_audit'),
        ),
    ]
