# Generated by Django 5.2.17 on 2026-08-23 19:06

import apps.invoicing.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_confirmed_partner_invoices(apps, schema_editor):
    """Map historical finalized B2B invoices without posting any new ledger rows."""
    Invoice = apps.get_model("invoicing", "SalesInvoice")
    candidates = Invoice.objects.filter(
        counterparty_type="business",
        buyer_business__isnull=False,
        trade__isnull=False,
        status="issued",
    )
    for invoice in candidates.iterator():
        paid = min(invoice.paid_amount, invoice.total_amount)
        credit = invoice.total_amount - paid
        invoice.status = "confirmed"
        invoice.confirmed_at = invoice.issued_at
        invoice.confirmed_by_id = invoice.issued_by_id
        invoice.cash_amount = paid
        invoice.credit_amount = credit
        invoice.cheque_amount = Decimal("0")
        if paid and credit:
            invoice.settlement_method = "mixed"
        elif paid:
            invoice.settlement_method = "cash"
        else:
            invoice.settlement_method = "credit"
        invoice.save(
            update_fields=[
                "status",
                "confirmed_at",
                "confirmed_by",
                "cash_amount",
                "credit_amount",
                "cheque_amount",
                "settlement_method",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_replace_request_capabilities'),
        ('invoicing', '0004_invoice_integrity_and_lifecycle'),
        ('trading', '0005_trade_proposals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('received', 'دریافت\u200cشده'), ('in_collection', 'در جریان وصول'), ('cleared', 'وصول\u200cشده'), ('bounced', 'برگشتی'), ('returned', 'مستردشده')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChequeReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(max_length=3)),
                ('reference_number', models.CharField(max_length=100)),
                ('bank', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField()),
                ('drawer_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('received', 'دریافت\u200cشده'), ('in_collection', 'در جریان وصول'), ('cleared', 'وصول\u200cشده'), ('bounced', 'برگشتی'), ('returned', 'مستردشده')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterpartyLinkProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=250)),
                ('import_batch_id', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('sent', 'ارسال\u200cشده'), ('rejected', 'ردشده'), ('confirmed', 'تأییدشده'), ('cancelled', 'لغوشده')], default='sent', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(editable=False, max_length=64)),
                ('seller_business_signature', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.invoicing.models.revision_signature_path)),
                ('seller_user_signature', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.invoicing.models.revision_signature_path)),
                ('buyer_business_signature', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.invoicing.models.revision_signature_path)),
                ('buyer_user_signature', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.invoicing.models.revision_signature_path)),
                ('offline_buyer_signature', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.invoicing.models.revision_signature_path)),
                ('sent_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('offline_signer_name', models.CharField(blank=True, max_length=200)),
                ('offline_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['revision_number'],
            },
        ),
        migrations.CreateModel(
            name='LocalCounterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='نام همکار محلی')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('normalized_phone', models.CharField(blank=True, db_index=True, editable=False, max_length=20)),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت خصوصی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('archived', 'بایگانی\u200cشده')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SettlementEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('cash', 'نقدی'), ('credit', 'اعتباری'), ('cheque', 'چک')], max_length=12)),
                ('event_type', models.CharField(choices=[('allocation', 'تخصیص'), ('reversal', 'برگشت')], default='allocation', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(max_length=3)),
                ('idempotency_key', models.CharField(editable=False, max_length=100, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvoiceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=apps.invoicing.models.personal_signature_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امضای شخصی فاکتور',
                'verbose_name_plural': 'امضاهای شخصی فاکتور',
            },
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoice',
            name='invoice_counterparty_matches_type',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoice',
            name='invoice_amounts_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoice',
            name='invoice_finalized_has_number',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoice',
            name='invoice_finalized_has_issued_at',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cheque_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cheque_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_invoices_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='current_revision_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='offline_confirmation',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sent_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_invoices_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='settlement_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('credit', 'اعتباری'), ('cheque', 'چک'), ('mixed', 'ترکیبی')], default='cash', max_length=12),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='counterparty_type',
            field=models.CharField(choices=[('business', 'همکار'), ('local', 'همکار محلی'), ('customer', 'مشتری')], default='business', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('awaiting_confirmation', 'در انتظار تأیید'), ('confirmed', 'تأییدشده'), ('issued', 'صادر شده'), ('cancelled_by_sender', 'لغوشده توسط فرستنده'), ('cancelled', 'باطل شده')], default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='chequeevent',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chequereceivable',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='invoicing.salesinvoice'),
        ),
        migrations.AddField(
            model_name='chequeevent',
            name='cheque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='invoicing.chequereceivable'),
        ),
        migrations.AddField(
            model_name='counterpartylinkproposal',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_links_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counterpartylinkproposal',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_links_proposed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counterpartylinkproposal',
            name='target_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_link_proposals', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='invoicerevision',
            name='decided_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='businesses.business'),
        ),
        migrations.AddField(
            model_name='invoicerevision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_revisions_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicerevision',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='invoicing.salesinvoice'),
        ),
        migrations.AddField(
            model_name='invoicerevision',
            name='offline_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offline_invoice_approvals_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicerevision',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_revisions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localcounterparty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localcounterparty',
            name='linked_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_local_counterparties', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='localcounterparty',
            name='owner_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_counterparties', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='counterpartylinkproposal',
            name='local_counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link_proposals', to='invoicing.localcounterparty'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='local_counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.localcounterparty'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('buyer_business__isnull', False), ('counterparty_type', 'business'), ('local_counterparty__isnull', True)), models.Q(('buyer_business__isnull', True), ('counterparty_type', 'local'), ('local_counterparty__isnull', False)), models.Q(('buyer_business__isnull', True), ('counterparty_type', 'customer'), ('local_counterparty__isnull', True)), _connector='OR'), name='invoice_counterparty_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('adjustment_amount__gte', 0), ('amount_due__gte', 0), ('cash_amount__gte', 0), ('cheque_amount__gte', 0), ('credit_amount__gte', 0), ('gross_subtotal__gte', 0), ('invoice_discount_amount__gte', 0), ('line_discount_total__gte', 0), ('paid_amount__gte', 0), ('previous_balance_snapshot__gte', 0), ('shipping_amount__gte', 0), ('tax_amount__gte', 0), ('total_amount__gte', 0)), name='invoice_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'awaiting_confirmation')), models.Q(('number', ''), _negated=True), _connector='OR'), name='invoice_finalized_has_number'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'awaiting_confirmation')), ('issued_at__isnull', False), _connector='OR'), name='invoice_finalized_has_issued_at'),
        ),
        migrations.AddField(
            model_name='settlementevent',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_events', to='invoicing.salesinvoice'),
        ),
        migrations.AddField(
            model_name='settlementevent',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementevent',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='invoicing.settlementevent'),
        ),
        migrations.AddField(
            model_name='settlementevent',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_events', to='invoicing.invoicerevision'),
        ),
        migrations.AddField(
            model_name='chequereceivable',
            name='settlement_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cheque', to='invoicing.settlementevent'),
        ),
        migrations.AddField(
            model_name='userinvoicesignature',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_signature', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='invoicerevision',
            constraint=models.UniqueConstraint(fields=('invoice', 'revision_number'), name='uniq_invoice_revision_number'),
        ),
        migrations.AddIndex(
            model_name='localcounterparty',
            index=models.Index(fields=['owner_business', 'status', 'normalized_name'], name='invoicing_l_owner_b_25839f_idx'),
        ),
        migrations.AddIndex(
            model_name='localcounterparty',
            index=models.Index(fields=['owner_business', 'normalized_phone'], name='invoicing_l_owner_b_f5d07a_idx'),
        ),
        migrations.AddConstraint(
            model_name='counterpartylinkproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('local_counterparty', 'target_business'), name='uniq_pending_counterparty_link'),
        ),
        migrations.AddConstraint(
            model_name='settlementevent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='settlementevent',
            constraint=models.UniqueConstraint(fields=('invoice', 'revision', 'kind', 'event_type'), name='uniq_settlement_kind_event_per_revision'),
        ),
        migrations.RunPython(backfill_confirmed_partner_invoices, migrations.RunPython.noop),
    ]
