# Generated by Django 5.1.15 on 2026-08-11 10:28

import apps.catalog.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('customer_name', models.CharField(blank=True, max_length=150, verbose_name='نام مشتری')),
                ('custom_message', models.TextField(blank=True, verbose_name='پیام اختصاصی')),
                ('share_token', models.CharField(default=apps.catalog.models.generate_share_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_catalogs', to='businesses.business')),
            ],
            options={
                'verbose_name': 'کاتالوگ اختصاصی',
                'verbose_name_plural': 'کاتالوگ\u200cهای اختصاصی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.customcatalog')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_catalog_items', to='inventory.inventorylot')),
            ],
            options={
                'verbose_name': 'آیتم کاتالوگ',
                'verbose_name_plural': 'آیتم\u200cهای کاتالوگ',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('catalog', 'lot'), name='uniq_lot_per_custom_catalog')],
            },
        ),
    ]
