# Generated by Django 5.1.15 on 2026-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcatalog',
            name='mode',
            field=models.CharField(choices=[('manual', 'انتخاب دستی'), ('rule', 'بر اساس فیلتر'), ('hybrid', 'فیلتر + انتخاب دستی')], default='manual', max_length=20, verbose_name='نوع کاتالوگ'),
        ),
        migrations.AddField(
            model_name='customcatalog',
            name='rules',
            field=models.JSONField(blank=True, default=dict, verbose_name='قوانین'),
        ),
        migrations.AddField(
            model_name='customcatalogitem',
            name='inclusion',
            field=models.CharField(choices=[('include', 'افزودن دستی'), ('exclude', 'حذف دستی')], default='include', max_length=20),
        ),
    ]
