# Generated by Django 5.1.15 on 2026-08-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('saved_search_match', 'تطابق جستجو'), ('partner_request', 'درخواست همکاری'), ('partner_decision', 'نتیجه همکاری'), ('reservation_request', 'درخواست رزرو'), ('reservation_decision', 'نتیجه رزرو'), ('reservation_expired', 'انقضای رزرو'), ('general', 'عمومی')], default='general', max_length=40),
        ),
    ]
